# Adapted from https://docs.docker.com/samples/django/

version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
      args:
        UID: ${USERID}
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"