# Adapted from https://docs.docker.com/samples/django/

version: "3.9"

volumes:
  mongo_db_data:  # Persistent mongo data.

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
      args:
        UID: ${USERID}
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      MONGO_USER: ${MONGO_ROOT_USERNAME}
      MONGO_PASS: ${MONGO_ROOT_PASSWORD}
      MONGO_HOST: mongo
      DJANGO_ADMIN_EMAIL: ${DJANGO_ADMIN_EMAIL}
      DJANGO_ADMIN_USER: ${DJANGO_ADMIN_USER}
      DJANGO_ADMIN_PASS: ${DJANGO_ADMIN_PASS}
    volumes:
      - .:/code
    ports:
      - "${WEB_APP_PORT}:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - "mongo_db_data:/data/db"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "${MONGO_UI_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo