# Generated by Django 3.2.5 on 2021-07-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team1Score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2Score',
            field=models.IntegerField(null=True),
        ),
    ]
